# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valinor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='valinor.proto',
  package='Valinor',
  syntax='proto3',
  serialized_pb=_b('\n\rvalinor.proto\x12\x07Valinor\"/\n\x0eValinorRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\x03\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1b\n\x0cValinorReply\x12\x0b\n\x03msg\x18\x01 \x01(\t2H\n\x07Valinor\x12=\n\tCallRobot\x12\x17.Valinor.ValinorRequest\x1a\x15.Valinor.ValinorReply\"\x00\x62\x06proto3')
)




_VALINORREQUEST = _descriptor.Descriptor(
  name='ValinorRequest',
  full_name='Valinor.ValinorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='Valinor.ValinorRequest.robot_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='Valinor.ValinorRequest.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=73,
)


_VALINORREPLY = _descriptor.Descriptor(
  name='ValinorReply',
  full_name='Valinor.ValinorReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Valinor.ValinorReply.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['ValinorRequest'] = _VALINORREQUEST
DESCRIPTOR.message_types_by_name['ValinorReply'] = _VALINORREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValinorRequest = _reflection.GeneratedProtocolMessageType('ValinorRequest', (_message.Message,), dict(
  DESCRIPTOR = _VALINORREQUEST,
  __module__ = 'valinor_pb2'
  # @@protoc_insertion_point(class_scope:Valinor.ValinorRequest)
  ))
_sym_db.RegisterMessage(ValinorRequest)

ValinorReply = _reflection.GeneratedProtocolMessageType('ValinorReply', (_message.Message,), dict(
  DESCRIPTOR = _VALINORREPLY,
  __module__ = 'valinor_pb2'
  # @@protoc_insertion_point(class_scope:Valinor.ValinorReply)
  ))
_sym_db.RegisterMessage(ValinorReply)



_VALINOR = _descriptor.ServiceDescriptor(
  name='Valinor',
  full_name='Valinor.Valinor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=104,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallRobot',
    full_name='Valinor.Valinor.CallRobot',
    index=0,
    containing_service=None,
    input_type=_VALINORREQUEST,
    output_type=_VALINORREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VALINOR)

DESCRIPTOR.services_by_name['Valinor'] = _VALINOR

# @@protoc_insertion_point(module_scope)
