# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shadowfax' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shadowfax
  pod 'Chatto', '= 3.3.1'
  pod 'ChattoAdditions', '=3.3.1'
  pod 'RealmSwift', '~> 3.5.0'
  # pod 'Moya', '~> 11.0.2'
  pod 'CocoaAsyncSocket', '~> 7.6.3'
  pod 'SwiftGRPC', '~> 0.4.3'
  pod 'Starscream', '~> 3.0.2'
  pod 'SwiftyRSA', '~> 1.4.0'
  pod 'CryptoSwift', '~> 0.9.0'

end
