# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imladris.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imladris.proto',
  package='Imladris',
  syntax='proto3',
  serialized_pb=_b('\n\x0eimladris.proto\x12\x08Imladris\"7\n\rSendToRequest\x12\x13\n\x0bsource_uuid\x18\x01 \x01(\t\x12\x11\n\tdist_uuid\x18\x02 \x01(\t\"F\n\x0bSendToReply\x12\x13\n\x0bstatus_code\x18\x01 \x01(\t\x12\x0f\n\x07\x64ist_ip\x18\x02 \x01(\t\x12\x11\n\tdist_port\x18\x03 \x01(\t\":\n\rSignalRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\"\n\x0bSignalReply\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"\x1e\n\rSigninRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"\"\n\x0bSigninReply\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32\xbe\x01\n\x08Imladris\x12:\n\x06SendTo\x12\x17.Imladris.SendToRequest\x1a\x15.Imladris.SendToReply\"\x00\x12:\n\x06Signin\x12\x17.Imladris.SigninRequest\x1a\x15.Imladris.SigninReply\"\x00\x12:\n\x06Signal\x12\x17.Imladris.SignalRequest\x1a\x15.Imladris.SignalReply\"\x00\x62\x06proto3')
)




_SENDTOREQUEST = _descriptor.Descriptor(
  name='SendToRequest',
  full_name='Imladris.SendToRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_uuid', full_name='Imladris.SendToRequest.source_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_uuid', full_name='Imladris.SendToRequest.dist_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=83,
)


_SENDTOREPLY = _descriptor.Descriptor(
  name='SendToReply',
  full_name='Imladris.SendToReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='Imladris.SendToReply.status_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_ip', full_name='Imladris.SendToReply.dist_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_port', full_name='Imladris.SendToReply.dist_port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=155,
)


_SIGNALREQUEST = _descriptor.Descriptor(
  name='SignalRequest',
  full_name='Imladris.SignalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Imladris.SignalRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal', full_name='Imladris.SignalRequest.signal', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='Imladris.SignalRequest.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=215,
)


_SIGNALREPLY = _descriptor.Descriptor(
  name='SignalReply',
  full_name='Imladris.SignalReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='Imladris.SignalReply.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=251,
)


_SIGNINREQUEST = _descriptor.Descriptor(
  name='SigninRequest',
  full_name='Imladris.SigninRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='Imladris.SigninRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=283,
)


_SIGNINREPLY = _descriptor.Descriptor(
  name='SigninReply',
  full_name='Imladris.SigninReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='Imladris.SigninReply.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=319,
)

DESCRIPTOR.message_types_by_name['SendToRequest'] = _SENDTOREQUEST
DESCRIPTOR.message_types_by_name['SendToReply'] = _SENDTOREPLY
DESCRIPTOR.message_types_by_name['SignalRequest'] = _SIGNALREQUEST
DESCRIPTOR.message_types_by_name['SignalReply'] = _SIGNALREPLY
DESCRIPTOR.message_types_by_name['SigninRequest'] = _SIGNINREQUEST
DESCRIPTOR.message_types_by_name['SigninReply'] = _SIGNINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendToRequest = _reflection.GeneratedProtocolMessageType('SendToRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDTOREQUEST,
  __module__ = 'imladris_pb2'
  # @@protoc_insertion_point(class_scope:Imladris.SendToRequest)
  ))
_sym_db.RegisterMessage(SendToRequest)

SendToReply = _reflection.GeneratedProtocolMessageType('SendToReply', (_message.Message,), dict(
  DESCRIPTOR = _SENDTOREPLY,
  __module__ = 'imladris_pb2'
  # @@protoc_insertion_point(class_scope:Imladris.SendToReply)
  ))
_sym_db.RegisterMessage(SendToReply)

SignalRequest = _reflection.GeneratedProtocolMessageType('SignalRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNALREQUEST,
  __module__ = 'imladris_pb2'
  # @@protoc_insertion_point(class_scope:Imladris.SignalRequest)
  ))
_sym_db.RegisterMessage(SignalRequest)

SignalReply = _reflection.GeneratedProtocolMessageType('SignalReply', (_message.Message,), dict(
  DESCRIPTOR = _SIGNALREPLY,
  __module__ = 'imladris_pb2'
  # @@protoc_insertion_point(class_scope:Imladris.SignalReply)
  ))
_sym_db.RegisterMessage(SignalReply)

SigninRequest = _reflection.GeneratedProtocolMessageType('SigninRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNINREQUEST,
  __module__ = 'imladris_pb2'
  # @@protoc_insertion_point(class_scope:Imladris.SigninRequest)
  ))
_sym_db.RegisterMessage(SigninRequest)

SigninReply = _reflection.GeneratedProtocolMessageType('SigninReply', (_message.Message,), dict(
  DESCRIPTOR = _SIGNINREPLY,
  __module__ = 'imladris_pb2'
  # @@protoc_insertion_point(class_scope:Imladris.SigninReply)
  ))
_sym_db.RegisterMessage(SigninReply)



_IMLADRIS = _descriptor.ServiceDescriptor(
  name='Imladris',
  full_name='Imladris.Imladris',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=322,
  serialized_end=512,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendTo',
    full_name='Imladris.Imladris.SendTo',
    index=0,
    containing_service=None,
    input_type=_SENDTOREQUEST,
    output_type=_SENDTOREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Signin',
    full_name='Imladris.Imladris.Signin',
    index=1,
    containing_service=None,
    input_type=_SIGNINREQUEST,
    output_type=_SIGNINREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Signal',
    full_name='Imladris.Imladris.Signal',
    index=2,
    containing_service=None,
    input_type=_SIGNALREQUEST,
    output_type=_SIGNALREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMLADRIS)

DESCRIPTOR.services_by_name['Imladris'] = _IMLADRIS

# @@protoc_insertion_point(module_scope)
