# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import imladris_pb2 as imladris__pb2


class ImladrisStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendTo = channel.unary_unary(
        '/Imladris.Imladris/SendTo',
        request_serializer=imladris__pb2.SendToRequest.SerializeToString,
        response_deserializer=imladris__pb2.SendToReply.FromString,
        )
    self.Signin = channel.unary_unary(
        '/Imladris.Imladris/Signin',
        request_serializer=imladris__pb2.SigninRequest.SerializeToString,
        response_deserializer=imladris__pb2.SigninReply.FromString,
        )
    self.Signal = channel.unary_unary(
        '/Imladris.Imladris/Signal',
        request_serializer=imladris__pb2.SignalRequest.SerializeToString,
        response_deserializer=imladris__pb2.SignalReply.FromString,
        )


class ImladrisServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendTo(self, request, context):
    """Gandalf <-> Gondor <-> Imladris
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Signin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Signal(self, request, context):
    """TODO: Signaling channel
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImladrisServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendTo': grpc.unary_unary_rpc_method_handler(
          servicer.SendTo,
          request_deserializer=imladris__pb2.SendToRequest.FromString,
          response_serializer=imladris__pb2.SendToReply.SerializeToString,
      ),
      'Signin': grpc.unary_unary_rpc_method_handler(
          servicer.Signin,
          request_deserializer=imladris__pb2.SigninRequest.FromString,
          response_serializer=imladris__pb2.SigninReply.SerializeToString,
      ),
      'Signal': grpc.unary_unary_rpc_method_handler(
          servicer.Signal,
          request_deserializer=imladris__pb2.SignalRequest.FromString,
          response_serializer=imladris__pb2.SignalReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Imladris.Imladris', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
