# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_account.proto',
  package='UserAccount',
  syntax='proto3',
  serialized_pb=_b('\n\x12user_account.proto\x12\x0bUserAccount\"E\n\rSignupRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x0fvalidation_code\x18\x03 \x01(\t\"7\n\rSigninRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x17\n\x0fvalidation_code\x18\x02 \x01(\t\"N\n\x12\x43hangePhoneRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x11\n\tnew_phone\x18\x02 \x01(\t\x12\x17\n\x0fvalidation_code\x18\x03 \x01(\t\"D\n\x10UserAccountReply\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"6\n\x12GetUserUUIDRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\ndist_phone\x18\x02 \x01(\t\";\n\x11GetUserUUIDReplay\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x11\n\tdist_uuid\x18\x02 \x01(\t2\xbe\x02\n\x0bUserAccount\x12\x45\n\x06Signup\x12\x1a.UserAccount.SignupRequest\x1a\x1d.UserAccount.UserAccountReply\"\x00\x12\x45\n\x06Signin\x12\x1a.UserAccount.SigninRequest\x1a\x1d.UserAccount.UserAccountReply\"\x00\x12O\n\x0b\x43hangePhone\x12\x1f.UserAccount.ChangePhoneRequest\x1a\x1d.UserAccount.UserAccountReply\"\x00\x12P\n\x0bGetUserUUID\x12\x1f.UserAccount.GetUserUUIDRequest\x1a\x1e.UserAccount.GetUserUUIDReplay\"\x00\x62\x06proto3')
)




_SIGNUPREQUEST = _descriptor.Descriptor(
  name='SignupRequest',
  full_name='UserAccount.SignupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='UserAccount.SignupRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserAccount.SignupRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validation_code', full_name='UserAccount.SignupRequest.validation_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=104,
)


_SIGNINREQUEST = _descriptor.Descriptor(
  name='SigninRequest',
  full_name='UserAccount.SigninRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='UserAccount.SigninRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validation_code', full_name='UserAccount.SigninRequest.validation_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=161,
)


_CHANGEPHONEREQUEST = _descriptor.Descriptor(
  name='ChangePhoneRequest',
  full_name='UserAccount.ChangePhoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='UserAccount.ChangePhoneRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_phone', full_name='UserAccount.ChangePhoneRequest.new_phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validation_code', full_name='UserAccount.ChangePhoneRequest.validation_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=241,
)


_USERACCOUNTREPLY = _descriptor.Descriptor(
  name='UserAccountReply',
  full_name='UserAccount.UserAccountReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='UserAccount.UserAccountReply.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='UserAccount.UserAccountReply.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='UserAccount.UserAccountReply.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=311,
)


_GETUSERUUIDREQUEST = _descriptor.Descriptor(
  name='GetUserUUIDRequest',
  full_name='UserAccount.GetUserUUIDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='UserAccount.GetUserUUIDRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_phone', full_name='UserAccount.GetUserUUIDRequest.dist_phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=367,
)


_GETUSERUUIDREPLAY = _descriptor.Descriptor(
  name='GetUserUUIDReplay',
  full_name='UserAccount.GetUserUUIDReplay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='UserAccount.GetUserUUIDReplay.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_uuid', full_name='UserAccount.GetUserUUIDReplay.dist_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=428,
)

DESCRIPTOR.message_types_by_name['SignupRequest'] = _SIGNUPREQUEST
DESCRIPTOR.message_types_by_name['SigninRequest'] = _SIGNINREQUEST
DESCRIPTOR.message_types_by_name['ChangePhoneRequest'] = _CHANGEPHONEREQUEST
DESCRIPTOR.message_types_by_name['UserAccountReply'] = _USERACCOUNTREPLY
DESCRIPTOR.message_types_by_name['GetUserUUIDRequest'] = _GETUSERUUIDREQUEST
DESCRIPTOR.message_types_by_name['GetUserUUIDReplay'] = _GETUSERUUIDREPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignupRequest = _reflection.GeneratedProtocolMessageType('SignupRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPREQUEST,
  __module__ = 'user_account_pb2'
  # @@protoc_insertion_point(class_scope:UserAccount.SignupRequest)
  ))
_sym_db.RegisterMessage(SignupRequest)

SigninRequest = _reflection.GeneratedProtocolMessageType('SigninRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNINREQUEST,
  __module__ = 'user_account_pb2'
  # @@protoc_insertion_point(class_scope:UserAccount.SigninRequest)
  ))
_sym_db.RegisterMessage(SigninRequest)

ChangePhoneRequest = _reflection.GeneratedProtocolMessageType('ChangePhoneRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHANGEPHONEREQUEST,
  __module__ = 'user_account_pb2'
  # @@protoc_insertion_point(class_scope:UserAccount.ChangePhoneRequest)
  ))
_sym_db.RegisterMessage(ChangePhoneRequest)

UserAccountReply = _reflection.GeneratedProtocolMessageType('UserAccountReply', (_message.Message,), dict(
  DESCRIPTOR = _USERACCOUNTREPLY,
  __module__ = 'user_account_pb2'
  # @@protoc_insertion_point(class_scope:UserAccount.UserAccountReply)
  ))
_sym_db.RegisterMessage(UserAccountReply)

GetUserUUIDRequest = _reflection.GeneratedProtocolMessageType('GetUserUUIDRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERUUIDREQUEST,
  __module__ = 'user_account_pb2'
  # @@protoc_insertion_point(class_scope:UserAccount.GetUserUUIDRequest)
  ))
_sym_db.RegisterMessage(GetUserUUIDRequest)

GetUserUUIDReplay = _reflection.GeneratedProtocolMessageType('GetUserUUIDReplay', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERUUIDREPLAY,
  __module__ = 'user_account_pb2'
  # @@protoc_insertion_point(class_scope:UserAccount.GetUserUUIDReplay)
  ))
_sym_db.RegisterMessage(GetUserUUIDReplay)



_USERACCOUNT = _descriptor.ServiceDescriptor(
  name='UserAccount',
  full_name='UserAccount.UserAccount',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=431,
  serialized_end=749,
  methods=[
  _descriptor.MethodDescriptor(
    name='Signup',
    full_name='UserAccount.UserAccount.Signup',
    index=0,
    containing_service=None,
    input_type=_SIGNUPREQUEST,
    output_type=_USERACCOUNTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Signin',
    full_name='UserAccount.UserAccount.Signin',
    index=1,
    containing_service=None,
    input_type=_SIGNINREQUEST,
    output_type=_USERACCOUNTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChangePhone',
    full_name='UserAccount.UserAccount.ChangePhone',
    index=2,
    containing_service=None,
    input_type=_CHANGEPHONEREQUEST,
    output_type=_USERACCOUNTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserUUID',
    full_name='UserAccount.UserAccount.GetUserUUID',
    index=3,
    containing_service=None,
    input_type=_GETUSERUUIDREQUEST,
    output_type=_GETUSERUUIDREPLAY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERACCOUNT)

DESCRIPTOR.services_by_name['UserAccount'] = _USERACCOUNT

# @@protoc_insertion_point(module_scope)
